# Query for preparing the data for ingestion into the search engine
# See also: https://collections.uu.nl/datasetregister

PREFIX ext: <https://example.org/>
PREFIX schema: <https://schema.org/>

CONSTRUCT {
  ?cho a schema:CreativeWork ;
    schema:name ?name ;
    schema:isPartOf ?dataset ;
    schema:description ?description ;
    schema:dateCreated ?dateCreated ;
    schema:creator ?creatorId, ?creatorName ;
    schema:genre ?genreId, ?genreName ;
    schema:material ?materialId, ?materialName ;
    schema:additionalType ?additionalTypeId, ?additionalTypeName ;
    schema:contentLocation ?contentLocationId, ?contentLocationName ;
    schema:associatedMedia ?associatedMediaId .

  ?dataset a ?datasetType ;
    schema:license <http://standaarden.overheid.nl/owms/terms/geslotenlicentie> ;
    schema:publisher <https://www.umu.nl/> .

  <http://standaarden.overheid.nl/owms/terms/geslotenlicentie> a ext:License ;
    schema:name "Gesloten licentie"@nl .

  <https://www.umu.nl/> a schema:Organization ;
    schema:name "Universiteitsmuseum Utrecht"@nl .

  ?creatorId a ext:Creator ;
    schema:name ?creatorName .

  ?genreId a ext:Genre ;
    schema:name ?genreName .

  ?materialId a ext:Material ;
    schema:name ?materialName .

  ?additionalTypeId a ext:AdditionalType ;
    schema:name ?additionalTypeName .

  ?contentLocationId a ext:ContentLocation ;
    schema:name ?contentLocationName .

  ?associatedMediaId a ?associatedMediaType ;
    schema:contentUrl ?contentUrl ;
    schema:thumbnailUrl ?thumbnailUrl ;
    schema:isBasedOn ?isBasedOn .

  ?isBasedOn schema:encodingFormat "application/ld+json;profile='http://iiif.io/api/image/3/context.json'" .
}
WHERE {
  #Example:
  BIND(<https://n2t.net/ark:/40020/collect163299> AS ?cho)

  ?cho a schema:CreativeWork ;
    schema:name ?name ;
    schema:isPartOf ?dataset .

  ?dataset a ?datasetType .

  OPTIONAL { ?cho schema:description ?description }
  OPTIONAL { ?cho schema:dateCreated ?dateCreated }

  OPTIONAL {
    ?cho schema:creator ?creator .
    ?creator schema:name ?creatorName
    BIND(IRI(CONCAT("https://example.org/persons/", MD5(STR(?creatorName)))) AS ?creatorId)
  }

  OPTIONAL {
    ?cho schema:genre ?genre .
    ?genre schema:name ?genreName
    BIND(IRI(CONCAT("https://example.org/terms/", MD5(STR(?genreName)))) AS ?genreId)
  }

  OPTIONAL {
    ?cho schema:material ?material .
    ?material schema:name ?materialName
    BIND(IRI(CONCAT("https://example.org/terms/", MD5(STR(?materialName)))) AS ?materialId)
  }

  OPTIONAL {
    ?cho schema:additionalType ?additionalType .
    ?additionalType schema:name ?additionalTypeName
    BIND(IRI(CONCAT("https://example.org/terms/", MD5(STR(?additionalTypeName)))) AS ?additionalTypeId)
  }

  OPTIONAL {
    ?cho schema:contentLocation ?contentLocation .
    ?contentLocation schema:name ?contentLocationName
    BIND(IRI(CONCAT("https://example.org/places/", MD5(STR(?contentLocationName)))) AS ?contentLocationId)
  }

  OPTIONAL {
    ?cho schema:associatedMedia ?associatedMedia .
    ?associatedMedia a ?associatedMediaType ;
      schema:contentUrl ?contentUrl ;
      schema:thumbnailUrl ?thumbnailUrl .

    # IIIF support is optional
    OPTIONAL {
      ?associatedMedia schema:isBasedOn ?isBasedOn .
    }

    BIND(IRI(CONCAT("https://example.org/media-objects/", MD5(STR(?contentUrl)))) AS ?associatedMediaId)
  }
}
