import {
  additionalTypesSchema,
  contentLocationsSchema,
  creatorsSchema,
  datasetsSchema,
  genresSchema,
  heritageObjectsSchema,
  licensesSchema,
  materialsSchema,
  mediaObjectsSchema,
  personsSchema,
  publishersSchema,
  subjectsSchema,
  termsSchema,
} from "@repo/typesense/schemas";

export const collectionSchemas = [
  additionalTypesSchema,
  contentLocationsSchema,
  creatorsSchema,
  datasetsSchema,
  genresSchema,
  heritageObjectsSchema,
  licensesSchema,
  materialsSchema,
  mediaObjectsSchema,
  personsSchema,
  publishersSchema,
  subjectsSchema,
  termsSchema,
];
